name: Build and Release Go Project

on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "linux/**"
      - "system/**"
      - ".github/workflows/go-release.yml"

permissions:
  contents: write

jobs:
  build:
    name: Build for multiple OS/ARCH
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build and zip for ${{ matrix.goos }}/${{ matrix.goarch }}
        run: |
          mkdir -p builds
          output_name="myproject"
          renamed_binary="system-${{ matrix.goos }}-${{ matrix.goarch }}"
          build_dir="builds/system-${{ matrix.goos }}-${{ matrix.goarch }}"
          binary_path="${build_dir}/${output_name}"
          renamed_path="${build_dir}/${renamed_binary}"

          mkdir -p "$build_dir"

          echo "Building for ${{ matrix.goos }}/${{ matrix.goarch }}..."
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "$binary_path" .
          chmod +x "$binary_path"

          mv "$binary_path" "$renamed_path"

          zip_name="system-${{ matrix.goos }}-${{ matrix.goarch }}.zip"
          (cd "$build_dir" && zip "$zip_name" "$renamed_binary")

      - name: Upload zipped build
        uses: actions/upload-artifact@v4
        with:
          name: system-${{ matrix.goos }}-${{ matrix.goarch }}
          path: builds/system-${{ matrix.goos }}-${{ matrix.goarch }}/*.zip

  release:
    name: Create 'latest' GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all zipped artifacts
        uses: actions/download-artifact@v4
        with:
          path: builds
          merge-multiple: true

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Create or update 'latest' release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view latest &>/dev/null; then
            echo "Release 'latest' exists. Deleting and recreating..."
            gh release delete latest --yes
          fi

          gh release create latest \
            --title "latest build" \
            --notes "Automated build for latest commit" \
            --latest

      - name: Upload all zips to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find builds -type f -name "*.zip" -exec gh release upload latest {} --clobber \;
